version: "3.9"
services:
  webapi:
    build: ./net-core-sample
    depends_on: 
      - redis
    ports:
      - 8000:80
    restart: always
    environment:
      RedisConnectionString: redis:6379
    env_file: .env
    networks:
      - compose_net
  redis:
    image: redis
    restart: always
    expose: 
      - 6379
    networks:
      - compose_net
networks:
  compose_net:
    driver: bridge